# Exercise - Rollback
AWSTemplateFormatVersion: 2010-09-09
Description: Create an EC2 instance and the associated security group
Resources:
  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      KeyName: webstack-key
      ImageId: "ami-0c4f7023847b90238"
      InstanceType: t3.micro
      Tags:
        - Key: Project
          Value: Gnosis
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
